Errandscall/Controllers/FleetController.cs
using Errandscall.Data;
using ErrandscallDatabase;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Errandscall.Controllers
{
    public class FleetController : BaseController
    {
        // GET: VehicleManagement
        public ActionResult VehicleManagement()
        {
            List<Vehicle> vehicles = db.Vehicle.ToList();
            return View(vehicles);
        }

        // GET: Request
        public ActionResult Request()
        {
            List<Request> requests = db.Request.ToList();
            return View(requests);
        }

        // GET: _NewVehicle
        [HttpGet]
        public ActionResult _NewVehicle(int? Id)
        {
            Vehicle vehicle = new Vehicle();
            if (Id != null && Id != 0)
            {
                vehicle = db.Vehicle.FirstOrDefault(v => v.Id == Id);

                ViewBag.VehicleMake = new SelectList(db.VehicleMake, "Id", "Description", vehicle.MakeId);
                ViewBag.VehicleModel = new SelectList(db.VehicleModel, "Id", "Description", vehicle.ModelId);
            }
            else
            {
                ViewBag.VehicleMake = new SelectList(db.VehicleMake, "Id", "Description");
                ViewBag.VehicleModel = new SelectList(db.VehicleModel, "Id", "Description");
            }

            return PartialView(vehicle);
        }

        public ActionResult ViewVehicle(int Id)
        {
            Vehicle vehicle = db.Vehicle.FirstOrDefault(v => v.Id == Id);

            return View(vehicle);
        }

        [HttpGet]
        public ActionResult _VehicleDocumet(int? Id, int vId)
        {
            VehicleDocument vehicleDocument = db.VehicleDocument.FirstOrDefault(v => v.VehicleId == Id);
            if (vehicleDocument != null)
            {
                ViewBag.DocumentType = new SelectList(db.DocumentType, "Id", "Description", vehicleDocument.TypeId);
            }
            else
            {
                vehicleDocument = new VehicleDocument();
                vehicleDocument.VehicleId = vId;
                ViewBag.DocumentType = new SelectList(db.DocumentType, "Id", "Description");
            }

            return PartialView(vehicleDocument);
        }

        [HttpPost]
        public ActionResult _VehicleDocumet(VehicleDocument vehicleDocument, HttpPostedFileBase VehicleDoc)
        {
            VehicleDocument rDocument = vehicleDocumentDoc(vehicleDocument, VehicleDoc);

            VehicleDocument document = db.VehicleDocument.FirstOrDefault(r => r.Id == vehicleDocument.Id);
            if (document != null)
            {
                document.document_name = rDocument.document_name;
                document.document_mime = rDocument.document_mime;
                document.document_data = rDocument.document_data;
                document.document_index = rDocument.document_index;
                document.TypeId = rDocument.TypeId;
                document.VehicleId = rDocument.VehicleId;
                document.LastModifiedDateTime = DateTime.Now;
                db.SaveChanges();
                ShowSuccess("Document was saved successfully");
            }
            else
            {
                rDocument.AddedOnDateTime = DateTime.Now;
                rDocument.LastModifiedDateTime = DateTime.Now;
                db.VehicleDocument.Add(rDocument);
                db.SaveChanges();
                ShowSuccess("Document was saved successfully");
            }

            return RedirectToAction("ViewVehicle", new { Id = vehicleDocument.VehicleId });
        }

        public VehicleDocument vehicleDocumentDoc(VehicleDocument request, HttpPostedFileBase VehicleDoc)
        {
            VehicleDocument vehicleDocument = new VehicleDocument();
            using (BinaryReader b = new BinaryReader(VehicleDoc.InputStream))
            {
                byte[] binData = b.ReadBytes(VehicleDoc.ContentLength);

                vehicleDocument.document_name = VehicleDoc.FileName;
                vehicleDocument.document_mime = VehicleDoc.ContentType;
                vehicleDocument.document_data = binData;
                vehicleDocument.document_index = 1;
                vehicleDocument.TypeId = request.TypeId;
                vehicleDocument.VehicleId = request.VehicleId;
            }

            return vehicleDocument;
        }

        // GET: Fleet/Create
        public ActionResult _Request(int VId)
        {
            var vehicle = db.Request.Where(v => v.VehicleId == VId && v.StatusId == 1).Select(s => s.ServiceId).ToList();
            Request request = new Request();

            request.Vehicle = db.Vehicle.FirstOrDefault(v => v.Id == VId);

            ViewBag.Service = new SelectList(db.Services.Where(s => !vehicle.Contains(s.Id)), "Id", "Description");

            return PartialView(request);
        }

        public ActionResult _EditRequest(int Id)
        {
            Request request = db.Request.FirstOrDefault(v => v.Id == Id);


            ViewBag.Service = new SelectList(db.Services, "Id", "Description", request.ServiceId);

            return PartialView(request);
        }

        public ActionResult ViewRequest(int Id)
        {
            Request request = db.Request.FirstOrDefault(v => v.Id == Id);

            return View(request);
        }

        [HttpGet]
        public ActionResult _RequestMessage(int Id)
        {

            Request request = db.Request.FirstOrDefault(r=>r.Id == Id);
            Message message = db.Message.FirstOrDefault(m=>m.RequestId == Id);
            if (message != null)
            {

            }
            else
            {
                message = new Message();
                message.Request = request;
                message.RequestId = request.Id;
                message.Client = request.Client;
            }

            return PartialView(message);
        }

        [HttpPost]
        public ActionResult _RequestMessage(Message message)
        {
            Request request = db.Request.FirstOrDefault(r => r.Id == message.RequestId);
            Message msg = new Message();
            msg.ClientId = CookieId();
            msg.RequestId = request.Id;
            msg.Message1 = message.Message1;
            msg.IsRead = false;
            msg.AddedOnDateTime = DateTime.Now;
            msg.LastModifiedDateTime = DateTime.Now;

            db.Message.Add(msg);
            db.SaveChanges();

            //TODO
            //Send notification to admin
            //

            ShowSuccess("Your message was sent successfully...");
            return RedirectToAction("ViewRequest", new { Id = message.RequestId });
        }

        [HttpGet]
        public ActionResult _RequestDocumet(int? Id, int rId)
        {
            RequestDocument requestDocument = db.RequestDocument.FirstOrDefault(v => v.RequestId == Id);
            if (requestDocument != null)
            {
                ViewBag.DocumentType = new SelectList(db.DocumentType, "Id", "Description", requestDocument.TypeId);
            }
            else
            {
                requestDocument = new RequestDocument();
                requestDocument.RequestId = rId;
                ViewBag.DocumentType = new SelectList(db.DocumentType, "Id", "Description");
            }

            return PartialView(requestDocument);
        }

        [HttpPost]
        public ActionResult _RequestDocumet(RequestDocument requestDocument, HttpPostedFileBase requestDoc)
        {
            RequestDocument rDocument = requestDocumentDoc(requestDocument, requestDoc);

            RequestDocument document = db.RequestDocument.FirstOrDefault(r => r.Id == requestDocument.Id);

            if (document != null)
            {
                document.document_name = rDocument.document_name;
                document.document_mime = rDocument.document_mime;
                document.document_data = rDocument.document_data;
                document.document_index = rDocument.document_index;
                document.TypeId = rDocument.TypeId;
                document.RequestId = rDocument.RequestId;
                document.LastModifiedDateTime = DateTime.Now;
                db.SaveChanges();
                ShowSuccess("Document was saved successfully");
            }
            else
            {
                rDocument.AddedOnDateTime = DateTime.Now;
                rDocument.LastModifiedDateTime = DateTime.Now;
                db.RequestDocument.Add(rDocument);
                db.SaveChanges();
                ShowSuccess("Document was saved successfully");
            }

            return RedirectToAction("ViewRequest", new { Id = requestDocument.RequestId });
        }

        public RequestDocument requestDocumentDoc(RequestDocument request, HttpPostedFileBase requestDoc)
        {
            RequestDocument requestDocument = new RequestDocument();
            using (BinaryReader b = new BinaryReader(requestDoc.InputStream))
            {
                byte[] binData = b.ReadBytes(requestDoc.ContentLength);

                requestDocument.document_name = requestDoc.FileName;
                requestDocument.document_mime = requestDoc.ContentType;
                requestDocument.document_data = binData;
                requestDocument.document_index = 1;
                requestDocument.TypeId = request.TypeId;
                requestDocument.RequestId = request.RequestId;
            }

            return requestDocument;
        }

        [HttpPost]
        public ActionResult _Request(Request request, string Comment)
        {
            var req = db.Request.FirstOrDefault(r => r.Id == request.Id);
            if (req != null)
            {
                //req.ClientId = CookieId();
                req.ServiceId = request.ServiceId;
                req.LastModifiedDateTime = DateTime.Now;
                db.SaveChanges();
            }
            else

Errandscall/Views/Fleet/Request.cshtml
@model IEnumerable<ErrandscallDatabase.Request>
@{
    ViewBag.Title = "Request Management";
}

<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3" style="background-color: #000">
            <h6 class="m-0 font-weight-bold text-primary float-left">Request List</h6>
            @*<h6 class="m-0 font-weight-bold text-primary float-right"><a href="@Url.Action("UserEdit")"><i class="fas fa-2x fa-plus-circle"></i></a></h6>*@
        </div>

        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Client)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Services)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.RequestStatus)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.LastModifiedDateTime)
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Client.Initials) @Html.DisplayFor(modelItem => item.Client.Surname)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Services.Description)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.RequestStatus.Description)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.LastModifiedDateTime)
                                </td>
                                <td>
                                    <a href="@Url.Action("ViewRequest", new { Id = item.Id })" class="btn btn-success btn-xs"><i> View</i></a>
                                    <a href="#" onclick="EditRequestShow(true, @item.Id)" class="btn btn-warning btn-xs"><i> Edit</i></a>
                                    <a href="#" data-toggle="modal" data-id="@item.Id" class="btn btn-danger btn-xs DeleteRequestModal"><i> Delete</i></a>
                                </td>
                            </tr>
                        }

                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>

<div class="modal fade" id="VehicleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <br />
    <div class="modal-dialog modal-lg " role="document">
        <div class="modal-content" style="background: white; border:0">
            <div class="modal-header">
                <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Request </h1>
                </div>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div id="exampleModalBody"></div>
            </div>
        </div>
    </div>
</div>


<script>
    document.onreadystatechange = function () {
        if (this.readyState === 'complete') {
            SetNavActive('Request');
        }
    };

    //_Request
    function EditRequestShow(Clear, VId) {

        $.ajax(
            {
                url: '@Url.Action("_EditRequest")?' +'&Id=' + VId,
                type: 'GET',
                success: function (result) {
                    if(Clear)
                        $('#exampleModalBody').html(result);
                    else
                        $('#exampleModalBody').html( result);
                    $('#VehicleModal').modal('show');

                }
            }
        );
    }
</script>

Errandscall/Views/Fleet/VehicleManagement.cshtml
@model IEnumerable<ErrandscallDatabase.Vehicle>
@{
    ViewBag.Title = "Vehicle Management";
}

<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3" style="background-color: #000">
            <h6 class="m-0 font-weight-bold text-primary float-left">Vehicle List</h6>
            <h6 class="m-0 font-weight-bold text-primary float-right"><a onclick="NewVehicleShow(true,null)"><i class="fas fa-2x fa-plus-circle"></i></a></h6>
        </div>

        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th></th>
                            <th>
                                @Html.DisplayNameFor(model => model.Client)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.VehicleMake)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.VehicleModel)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.VIN)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Reg)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.DayOfExpire)
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var item in Model)
                        {
                            <tr>
                                <td> @Html.DisplayFor(modelItem => item.Id)</td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Client.Initials) @Html.DisplayFor(modelItem => item.Client.Surname)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.VehicleMake.Description)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.VehicleModel.Description)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.VIN)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Reg)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.DayOfExpire)
                                </td>
                                <td>
                                    <a href="@Url.Action("ViewVehicle", new { Id = item.Id })" class="btn btn-success btn-xs"><i> View</i></a>
                                    <a href="#" onclick="RequestServiceShow(true, @item.Id)" class="btn btn-info btn-xs"><i> Request</i></a>
                                    <a href="#" onclick="NewVehicleShow(true, @item.Id)" class="btn btn-warning btn-xs"><i> Edit</i></a>
                                    <a href="#" data-toggle="modal" data-id="@item.Id" class="btn btn-danger btn-xs DeleteVehicleModal"><i> Delete</i></a>
                                </td>
                            </tr>
                        }

                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>

<div class="modal fade" id="VehicleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <br />
    <div class="modal-dialog modal-lg " role="document">
        <div class="modal-content" style="background: white; border:0">
            <div class="modal-header">
                <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Request </h1>
                </div>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div id="exampleModalBody"></div>
            </div>
        </div>
    </div>
</div>

<script>
    document.onreadystatechange = function () {
        if (document.readyState == "complete") {
            SetNavActive( 'VehicleManagement');
        }
    }

    function NewVehicleShow(Clear, Id) {        
        $.ajax(
            {
                url: '@Url.Action("_NewVehicle")?' + '&Id=' + Id,
                type: 'GET',
                success: function (result) {
                    if(Clear)
                        $('#exampleModalBody').html(result);
                    else
                        $('#exampleModalBody').html( result);
                    $('#VehicleModal').modal('show');

                }
            }
        );
    }

    //_Request
    function RequestServiceShow(Clear, VId) {

        $.ajax(
            {
                url: '@Url.Action("_Request")?' +'&VId=' + VId,
                type: 'GET',
                success: function (result) {
                    if(Clear)
                        $('#exampleModalBody').html(result);
                    else
                        $('#exampleModalBody').html( result);
                    $('#VehicleModal').modal('show');

                }
            }
        );
    }
</script>

Errandscall/Views/Fleet/_EditRequest.cshtml
@model ErrandscallDatabase.Request

@using (Html.BeginForm("_Request", "Fleet", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="row justify-content-center">
        <div class="card-body p-0">

            <!-- Nested Row within Card Body -->
            <div class="row">

                <div class="col-lg-12">
                    <div class="p-5">

                        <div class="form-group">
                            @Html.HiddenFor(m => m.Id)
                            @Html.Hidden("VehicleId", Model.Vehicle.Id)
                            @Html.TextBoxFor(m => m.Vehicle.DayOfExpire, new { @class = "form-control form-control-user", @required = "required", @readonly = "readonly" })
                            @Html.ValidationMessageFor(model => model.Vehicle.DayOfExpire, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            @Html.TextBoxFor(m => m.Vehicle.Reg, new { @class = "form-control form-control-user", @required = "required", @readonly = "readonly" })
                            @Html.ValidationMessageFor(model => model.Vehicle.Reg, "", new { @class = "text-danger" })

                        </div>
                        <div class="form-group">
                            @Html.TextBoxFor(m => m.Vehicle.VehicleMake.Description, new { @class = "form-control form-control-user", @required = "required", @readonly = "readonly" })
                            @Html.ValidationMessageFor(model => model.Vehicle.VehicleMake.Description, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            @Html.DropDownList("ServiceId", ViewBag.Service as SelectList, "--- Select Service Type ---", new { @id = "MakeId", @class = "form-control form-control-user ServiceId", @onchange = "VehicleMakeChange()", @required = "@required" })
                            @Html.ValidationMessageFor(model => model.ServiceId, "", new { @class = "text-danger" })

                        </div>
                        @*<div class="form-group">
                            <input style="width:100%;" type="file" class="form-control" name="RequestDoCs" id="RequestDoCs" multiple="multiple" />
                        </div>*@
                        <div class="form-group">
                            <textarea name="Comment" class="form-control form-control-user" rows="4" placeholder="Enter motivitional comment..." required></textarea>
                        </div>
                        <button type="submit" class="btn btn-primary btn-user" id="">
                            Submit
                        </button>

                    </div>
                </div>

            </div>
        </div>

    </div>


}

@*<div>
        @Html.ActionLink("Back to List", "Index")
    </div>*@
<script>
    $(document).ready(function () {

        $(function () {
            $(".ServiceId").chosen({ width: "100%" });

            $("[data-mask]").inputmask();

        });


    })
</script>

Errandscall/Views/Fleet/_NewVehicle.cshtml
@model ErrandscallDatabase.Vehicle

@using (Html.BeginForm("_NewVehicle", "Fleet", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="row justify-content-center">
        <div class="card-body p-0">


            <!-- Nested Row within Card Body -->
            <div class="row">

                <div class="col-lg-12">
                    <div class="p-5">

                        <div class="form-group">
                            @Html.HiddenFor(m => m.Id, new { @id = "VehicleId" })
                            @Html.TextBoxFor(m => m.VIN, new { @class = "form-control form-control-user", @placeholder = "Enter Vehicle Vin...", @required = "required" })
                            @Html.ValidationMessageFor(model => model.VIN, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            @Html.TextBoxFor(m => m.Reg, new { @class = "form-control form-control-user", @placeholder = "Enter Vehicle Registration...", @required = "required" })
                            @Html.ValidationMessageFor(model => model.Reg, "", new { @class = "text-danger" })

                        </div>
                        <div class="form-group">
                            @Html.TextBoxFor(m => m.DayOfExpire, new { @class = "form-control form-control-user", @id = "DayOfExpire", @placeholder = "Date of Expire...", @required = "required", autocomplete = "off" })
                            @Html.ValidationMessageFor(model => model.DayOfExpire, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            @Html.DropDownList("MakeId", ViewBag.VehicleMake as SelectList, "--- Select Vehicle Make ---", new { @class = "form-control form-control-user", @onchange = "VehicleMakeChange()", @required = "@required" })
                            @Html.ValidationMessageFor(model => model.DayOfExpire, "", new { @class = "text-danger" })

                        </div>
                        <div class="form-group">
                            @Html.DropDownList("ModelId", ViewBag.VehicleModel as SelectList, "--- Select Vehicle Model ---", new { @id = "ModelResult", @class = "form-control form-control-user ModelId", @required = "@required" })
                            @Html.ValidationMessageFor(model => model.DayOfExpire, "", new { @class = "text-danger" })

                        </div>
                        @*<div class="form-group">
                            <input style="width:100%;" type="file" class="form-control" name="VehicleDoCs" id="VehicleDoCs" multiple="multiple" />
                        </div>*@
                        @*<div class="form-group">
                                @Html.TextAreaFor(m => m.DayOfExpire, new { @class = "form-control form-control-user", @placeholder = "Enter motivitional comment...", @rows = "4", @required = "required" })
                                @Html.ValidationMessageFor(model => model.DayOfExpire, "", new { @class = "text-danger" })
                            </div>*@
                        <button type="submit" class="btn btn-primary btn-user" id="">
                            Submit
                        </button>

                    </div>
                </div>

            </div>
        </div>

    </div>


}

@*<div>
        @Html.ActionLink("Back to List", "VehicleManagement")
    </div>*@

<script>

    $(document).ready(function () {

        $("#DayOfExpire").datetimepicker({
            timepicker: false,
            format: 'm/Y'
        });

        $(function () {
            $("#MakeId").chosen({ width: "100%" });
            $(".ModelId").chosen({ width: "100%" });

            $("[data-mask]").inputmask();

        });


    })

    function VehicleMakeChange() {
        //alert($('#MakeId').val());
        var id = $('#MakeId').val();
        $.ajax({
            url: '@Url.Action("VehicleModel")',
            method: "POST",
            data: { id: id},
            success: function (data)
            {
                //debugger
                var s = "<option value=''>--- Select Vehicle Model ---</option>";
                for (var i = 0; i < data.length; i++) {
                    s += "<option value='" + data[i].Value + "'> " + data[i].Text + "</option>";
                }
                $("#ModelResult").html(s);
            }
        });


        $("#MakeId").chosen({ width: "100%" });
        $(".ModelId").chosen({ width: "100%" });
    }
</script>

Errandscall/Views/Fleet/_RequestDocumet.cshtml
@model ErrandscallDatabase.RequestDocument

@using (Html.BeginForm("_RequestDocumet", "Fleet", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="modal-header">
        <div class="text-center">
            <h1 class="h4 text-gray-900 mb-4">Document </h1>
        </div>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.RequestId)

        <div class="form-group">
            @Html.Label("Document Type", htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-12">
                @Html.DropDownList("TypeId", ViewBag.DocumentType as SelectList, "--- Select Type ---", new { @class = "form-control form-control-user", @required = "@required" })
                @Html.ValidationMessageFor(model => model.TypeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label>Attach Document</label>
            <div class="col-md-12">
                <div class="form-group">
                    <input style="width:100%;" type="file" class="form-control" name="requestDoc" id="requestDoc" />
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-4 col-md-12">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    </div>
}


<script>
    $(document).ready(function () {

        $(function () {
            $("#TypeId").chosen({ width: "100%" });

            $("[data-mask]").inputmask();

        });


    })
</script>

Errandscall/Views/Fleet/_VehicleDocumet.cshtml
@model ErrandscallDatabase.VehicleDocument

@using (Html.BeginForm("_VehicleDocumet", "Fleet", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.VehicleId)

    <div class="form-group">

        @Html.Label("Document Type", htmlAttributes: new { @class = "control-label col-md-4" })
        <div class="col-md-12">
            @Html.DropDownList("TypeId", ViewBag.DocumentType as SelectList, "--- Select Type ---", new { @class = "form-control form-control-user", @required = "@required" })
            @Html.ValidationMessageFor(model => model.TypeId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label>Attach Document</label>
        <div class="col-md-12">
            <div class="form-group">
                <input style="width:100%;" type="file" class="form-control" name="VehicleDoc" id="VehicleDoc" />
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
}

<script>
    $(document).ready(function () {

        $(function () {
            $("#TypeId").chosen({ width: "100%" });

            $("[data-mask]").inputmask();

        });


    })
</script>